version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          - v1-dependencies-

      - run:
          name: Compile
          command: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - "~/.sbt"
            - "target/resolution-cache"
            - "target/streams"
            - "project/target/resolution-cache"
            - "project/target/streams"
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run:
          name: Run tests
          command: cat /dev/null | sbt test:test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit